[versions]
agp = "8.13.1"
pgp = "0.9.5"
annotationsApi = "6.0.53"
appcompat = "1.7.1"
espressoCore = "3.7.0"
fragment = "1.8.9"
grpcAndroid = "1.76.0"
grpcOkhttp = "1.76.0"
grpcProtobufLite = "1.76.0"
guava = "33.5.0-android"
junit = "4.13.2"
junitVersion = "1.3.0"
lifecycleViewmodel = "2.9.4"
material = "1.13.0"
preference = "1.2.1"
recyclerview = "1.4.0"
recyclerviewSelection = "1.2.0"
roomRuntime = "2.8.3"

[libraries]
annotations-api = { module = "org.apache.tomcat:annotations-api", version.ref = "annotationsApi" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
grpc-android = { module = "io.grpc:grpc-android", version.ref = "grpcAndroid" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpcOkhttp" }
grpc-protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpcProtobufLite" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpcProtobufLite" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleViewmodel" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleViewmodel" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleViewmodel" }
material = { module = "com.google.android.material:material", version.ref = "material" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerviewSelection" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-guava = { module = "androidx.room:room-guava", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
protobuf = { id = "com.google.protobuf", version.ref = "pgp" }
